### ISSUE TITLE
How to use docker-smtp with a WordPress container?

### ISSUE THREAD

**Issue by silviubogan** [namshi/docker-smtp#67]
I have this in my *docker-compose.yml* (replace `...` with anything valid):

```
wordpress:
    container_name: ...wordpress_1
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
        volume:
          nocopy: true
    restart: "no"
    environment:
      WORDPRESS_DB_NAME: '...'
      WORDPRESS_DB_USER: '...'
      WORDPRESS_DB_PASSWORD: '...'
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_TABLE_PREFIX: 'wp_'
      WORDPRESS_AUTH_KEY: '...'
      WORDPRESS_SECURE_AUTH_KEY: '...'
      WORDPRESS_LOGGED_IN_KEY: '...'
      WORDPRESS_NONCE_KEY: '...'
      WORDPRESS_AUTH_SALT: '...'
      WORDPRESS_SECURE_AUTH_SALT: '...'
      WORDPRESS_LOGGED_IN_SALT: '...'
      WORDPRESS_NONCE_SALT: '...'
```

and this:

```
  smtp:
    image: namshi/smtp
    container_name: ...smtp_relay_1
    restart: "no"
    ports:
      - "25:25"
```

It seems that the SMTP is not accessible from the Contact Form 7 WordPress plugin which I use through the REST API. How can I test the smtp container in a fast and good way or how can I change the `docker-compose.yml` file to make it work?

When I run `$ docker-compose up` I do not get errors.

The JSON object I get in the browser is this:

```
{into: "#", status: "mail_failed", message: "There was an error trying to send your message. Please try again later."}
```

The related forum question is [here](https://wordpress.org/support/topic/how-to-use-the-contact-form-7-rest-api/).

Thank you.
